# Generated by Django 5.2.6 on 2025-09-14 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('driving_hours', models.FloatField(default=0)),
                ('on_duty_hours', models.FloatField(default=0)),
                ('off_duty_hours', models.FloatField(default=0)),
                ('sleeper_hours', models.FloatField(default=0)),
                ('hours_left_in_cycle', models.FloatField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('bol_number', models.CharField(blank=True, max_length=100, null=True)),
                ('shipper', models.CharField(blank=True, max_length=100, null=True)),
                ('commodity', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=100)),
                ('pickup_location', models.CharField(max_length=100)),
                ('dropoff_location', models.CharField(max_length=100)),
                ('current_cycle_used', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrier_name', models.CharField(default='Unknown Carrier', max_length=255)),
                ('main_office_address', models.CharField(default='', max_length=200)),
                ('home_terminal_address', models.CharField(default='', max_length=200)),
                ('tractor_number', models.CharField(default='', max_length=50)),
                ('trailer_number', models.CharField(default='', max_length=50)),
                ('license_plate', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Off Duty', 'Off Duty'), ('Sleeper Berth', 'Sleeper Berth'), ('Driving', 'Driving'), ('On Duty', 'On Duty')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('remarks', models.TextField(blank=True, default='')),
                ('logsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='truck_app.logsheet')),
            ],
        ),
        migrations.AddField(
            model_name='logsheet',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logsheets', to='truck_app.trip'),
        ),
    ]
